// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crypto/crypto.proto

package crypto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Crypto struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Votes                int64    `protobuf:"varint,3,opt,name=votes,proto3" json:"votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Crypto) Reset()         { *m = Crypto{} }
func (m *Crypto) String() string { return proto.CompactTextString(m) }
func (*Crypto) ProtoMessage()    {}
func (*Crypto) Descriptor() ([]byte, []int) {
	return fileDescriptor_27e1fe69dc202ca1, []int{0}
}

func (m *Crypto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crypto.Unmarshal(m, b)
}
func (m *Crypto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crypto.Marshal(b, m, deterministic)
}
func (m *Crypto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crypto.Merge(m, src)
}
func (m *Crypto) XXX_Size() int {
	return xxx_messageInfo_Crypto.Size(m)
}
func (m *Crypto) XXX_DiscardUnknown() {
	xxx_messageInfo_Crypto.DiscardUnknown(m)
}

var xxx_messageInfo_Crypto proto.InternalMessageInfo

func (m *Crypto) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Crypto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Crypto) GetVotes() int64 {
	if m != nil {
		return m.Votes
	}
	return 0
}

type GetCryptoByIdRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCryptoByIdRequest) Reset()         { *m = GetCryptoByIdRequest{} }
func (m *GetCryptoByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetCryptoByIdRequest) ProtoMessage()    {}
func (*GetCryptoByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27e1fe69dc202ca1, []int{1}
}

func (m *GetCryptoByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCryptoByIdRequest.Unmarshal(m, b)
}
func (m *GetCryptoByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCryptoByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetCryptoByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCryptoByIdRequest.Merge(m, src)
}
func (m *GetCryptoByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetCryptoByIdRequest.Size(m)
}
func (m *GetCryptoByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCryptoByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCryptoByIdRequest proto.InternalMessageInfo

func (m *GetCryptoByIdRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateCryptoRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Votes                int64    `protobuf:"varint,2,opt,name=votes,proto3" json:"votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCryptoRequest) Reset()         { *m = CreateCryptoRequest{} }
func (m *CreateCryptoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCryptoRequest) ProtoMessage()    {}
func (*CreateCryptoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27e1fe69dc202ca1, []int{2}
}

func (m *CreateCryptoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCryptoRequest.Unmarshal(m, b)
}
func (m *CreateCryptoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCryptoRequest.Marshal(b, m, deterministic)
}
func (m *CreateCryptoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCryptoRequest.Merge(m, src)
}
func (m *CreateCryptoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCryptoRequest.Size(m)
}
func (m *CreateCryptoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCryptoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCryptoRequest proto.InternalMessageInfo

func (m *CreateCryptoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCryptoRequest) GetVotes() int64 {
	if m != nil {
		return m.Votes
	}
	return 0
}

type CryptoResponse struct {
	Crypto               *Crypto  `protobuf:"bytes,1,opt,name=crypto,proto3" json:"crypto,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CryptoResponse) Reset()         { *m = CryptoResponse{} }
func (m *CryptoResponse) String() string { return proto.CompactTextString(m) }
func (*CryptoResponse) ProtoMessage()    {}
func (*CryptoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27e1fe69dc202ca1, []int{3}
}

func (m *CryptoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CryptoResponse.Unmarshal(m, b)
}
func (m *CryptoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CryptoResponse.Marshal(b, m, deterministic)
}
func (m *CryptoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CryptoResponse.Merge(m, src)
}
func (m *CryptoResponse) XXX_Size() int {
	return xxx_messageInfo_CryptoResponse.Size(m)
}
func (m *CryptoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CryptoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CryptoResponse proto.InternalMessageInfo

func (m *CryptoResponse) GetCrypto() *Crypto {
	if m != nil {
		return m.Crypto
	}
	return nil
}

func (m *CryptoResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Crypto)(nil), "Crypto")
	proto.RegisterType((*GetCryptoByIdRequest)(nil), "GetCryptoByIdRequest")
	proto.RegisterType((*CreateCryptoRequest)(nil), "CreateCryptoRequest")
	proto.RegisterType((*CryptoResponse)(nil), "CryptoResponse")
}

func init() { proto.RegisterFile("crypto/crypto.proto", fileDescriptor_27e1fe69dc202ca1) }

var fileDescriptor_27e1fe69dc202ca1 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3f, 0x4f, 0x84, 0x30,
	0x18, 0xc6, 0xd3, 0xde, 0x89, 0xf1, 0xd5, 0x3b, 0x93, 0xf7, 0x30, 0x21, 0x2e, 0x12, 0x06, 0xc3,
	0x54, 0x13, 0x8c, 0x71, 0x34, 0x81, 0x81, 0xb8, 0xd6, 0x4f, 0x80, 0xf0, 0x0e, 0x0c, 0x52, 0x6c,
	0x2b, 0x09, 0x93, 0x5f, 0xdd, 0xd8, 0x42, 0x82, 0xc8, 0x04, 0x4f, 0xf3, 0xfc, 0xe9, 0xaf, 0x70,
	0xaa, 0xf5, 0xd8, 0x5b, 0xf5, 0xe0, 0x3f, 0xa2, 0xd7, 0xca, 0xaa, 0x24, 0x87, 0xa0, 0x70, 0x1a,
	0x8f, 0xc0, 0xdb, 0x26, 0x62, 0x31, 0x4b, 0xf7, 0x92, 0xb7, 0x0d, 0x22, 0xec, 0xbb, 0xea, 0x83,
	0x22, 0x1e, 0xb3, 0xf4, 0x42, 0xba, 0x7f, 0x0c, 0xe1, 0x6c, 0x50, 0x96, 0x4c, 0xb4, 0x8b, 0x59,
	0xba, 0x93, 0x5e, 0x24, 0xf7, 0x10, 0x96, 0x64, 0x7d, 0x4d, 0x3e, 0xbe, 0x36, 0x92, 0x3e, 0xbf,
	0xc8, 0xd8, 0x75, 0x63, 0xf2, 0x02, 0xa7, 0x42, 0x53, 0x65, 0xc9, 0x5b, 0x67, 0xdb, 0x3c, 0xc4,
	0xb6, 0x86, 0xf8, 0x72, 0xa8, 0x84, 0xe3, 0x1c, 0x35, 0xbd, 0xea, 0x0c, 0xe1, 0x1d, 0x04, 0x1e,
	0xc7, 0xa5, 0x2f, 0xb3, 0x73, 0x31, 0x19, 0xa6, 0xe3, 0xdf, 0x22, 0xd2, 0x5a, 0xe9, 0x09, 0xc3,
	0x8b, 0xec, 0x1b, 0x0e, 0xde, 0xf7, 0x46, 0x7a, 0x68, 0x6b, 0xc2, 0x67, 0x38, 0xfc, 0x41, 0xc0,
	0x1b, 0xb1, 0x85, 0x74, 0x7b, 0x2d, 0x56, 0x17, 0x78, 0x82, 0xab, 0x25, 0x13, 0x86, 0x62, 0x03,
	0xf1, 0x5f, 0xec, 0x3d, 0x70, 0xaf, 0xff, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x2e, 0xfe,
	0x4d, 0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CryptoServiceClient is the client API for CryptoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CryptoServiceClient interface {
	GetCryptoById(ctx context.Context, in *GetCryptoByIdRequest, opts ...grpc.CallOption) (*CryptoResponse, error)
	CreateCrypto(ctx context.Context, in *CreateCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error)
}

type cryptoServiceClient struct {
	cc *grpc.ClientConn
}

func NewCryptoServiceClient(cc *grpc.ClientConn) CryptoServiceClient {
	return &cryptoServiceClient{cc}
}

func (c *cryptoServiceClient) GetCryptoById(ctx context.Context, in *GetCryptoByIdRequest, opts ...grpc.CallOption) (*CryptoResponse, error) {
	out := new(CryptoResponse)
	err := c.cc.Invoke(ctx, "/CryptoService/GetCryptoById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) CreateCrypto(ctx context.Context, in *CreateCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error) {
	out := new(CryptoResponse)
	err := c.cc.Invoke(ctx, "/CryptoService/CreateCrypto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoServiceServer is the server API for CryptoService service.
type CryptoServiceServer interface {
	GetCryptoById(context.Context, *GetCryptoByIdRequest) (*CryptoResponse, error)
	CreateCrypto(context.Context, *CreateCryptoRequest) (*CryptoResponse, error)
}

// UnimplementedCryptoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCryptoServiceServer struct {
}

func (*UnimplementedCryptoServiceServer) GetCryptoById(ctx context.Context, req *GetCryptoByIdRequest) (*CryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCryptoById not implemented")
}
func (*UnimplementedCryptoServiceServer) CreateCrypto(ctx context.Context, req *CreateCryptoRequest) (*CryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCrypto not implemented")
}

func RegisterCryptoServiceServer(s *grpc.Server, srv CryptoServiceServer) {
	s.RegisterService(&_CryptoService_serviceDesc, srv)
}

func _CryptoService_GetCryptoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCryptoByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).GetCryptoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoService/GetCryptoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).GetCryptoById(ctx, req.(*GetCryptoByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_CreateCrypto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).CreateCrypto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CryptoService/CreateCrypto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).CreateCrypto(ctx, req.(*CreateCryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CryptoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CryptoService",
	HandlerType: (*CryptoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCryptoById",
			Handler:    _CryptoService_GetCryptoById_Handler,
		},
		{
			MethodName: "CreateCrypto",
			Handler:    _CryptoService_CreateCrypto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crypto/crypto.proto",
}
